# -*- coding: utf-8 -*-
"""sft

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14PzbkKNTHw8fpy2MnT8mLnY_X_wh35vx
"""

# Cell 1: Check GPU
!nvidia-smi

# Commented out IPython magic to ensure Python compatibility.
# Cell 2: Clone your repo
!git clone https://github.com/dcyforjob2020/ai-interview-coach.git
# %cd ai-interview-coach

# Cell 3: Install dependencies
!pip install -q -U \
  "transformers==4.46.3" \
  accelerate \
  peft \
  datasets \
  bitsandbytes \
  trl \
  sentencepiece \
  "protobuf<6"

import torch
import transformers
import peft
import trl
import bitsandbytes

print("torch:", torch.__version__)
print("cuda available:", torch.cuda.is_available())
print("transformers:", transformers.__version__)
print("peft:", peft.__version__)
print("trl:", trl.__version__)

# Cell 4: Optional, login to Hugging Face
# Qwen models are usually public, but login helps if Colab hits access/rate limits.
from huggingface_hub import notebook_login
notebook_login()

# Cell 5: Build the SFT dataset from preference pairs
!python train/sft/build_sft_dataset.py \
  --input train/preference_pairs.jsonl \
  --output train/sft/sft_dataset.jsonl

# Cell 6: Quick sanity check of the SFT dataset
import json

path = "train/sft/sft_dataset.jsonl"

with open(path, "r", encoding="utf-8") as f:
    first = json.loads(next(f))

print(first.keys())
print(first["id"])
print(first["messages"][0])
print(first["messages"][1]["content"][:500])
print(first["messages"][2]["content"][:500])

# Cell 7: Train SFT with QLoRA
# For T4 GPU, 1024 max seq length is safer.
# If you have L4/A100, you can try 2048.
!python train/sft/train_sft_qlora.py \
  --model Qwen/Qwen2.5-3B-Instruct \
  --data train/sft/sft_dataset.jsonl \
  --output-dir train/model/sft_adapter \
  --max-seq-length 1024 \
  --epochs 1 \
  --batch-size 1 \
  --grad-accum 8 \
  --learning-rate 1e-4 \
  --save-steps 200 \
  --logging-steps 10

# Cell 8: Zip the trained adapter so you can download it
!zip -r sft_adapter.zip train/model/sft_adapter

# Cell 9: Download the adapter
from google.colab import files
files.download("sft_adapter.zip")

!zip -r sft_adapter_final_only.zip \
  train/model/sft_adapter/adapter_config.json \
  train/model/sft_adapter/adapter_model.safetensors \
  train/model/sft_adapter/tokenizer.json \
  train/model/sft_adapter/tokenizer_config.json \
  train/model/sft_adapter/special_tokens_map.json \
  train/model/sft_adapter/vocab.json \
  train/model/sft_adapter/merges.txt \
  train/model/sft_adapter/README.md \
  train/model/sft_adapter/added_tokens.json \
  train/model/sft_adapter/training_args.bin

from google.colab import files
files.download("sft_adapter_final_only.zip")

from huggingface_hub import notebook_login
notebook_login()

from huggingface_hub import HfApi

api = HfApi()

repo_id = "Hank122222222/ai-interview-coach-sft-adapter"

api.create_repo(
    repo_id=repo_id,
    repo_type="model",
    private=False,
    exist_ok=True,
)

api.upload_folder(
    folder_path="train/model/sft_adapter",
    repo_id=repo_id,
    repo_type="model",
    commit_message="Upload SFT LoRA adapter",
    ignore_patterns=[
        "checkpoint-*",
        "optimizer.pt",
        "scheduler.pt",
        "rng_state.pth",
        "trainer_state.json",
    ],
)

print("Uploaded to:", f"https://huggingface.co/{repo_id}")